#! ---------------------------------------------------------------
#!  ▄▀▄ █▀▄ ▄▀▀ ▀ █▀▄ ▀ ▄▀▄ █▄░█
#! █░█ █▀█ ░▀▄ █ █░█ █ █▀█ █░▀█
#!░▀░ ▀▀░ ▀▀░ ▀ ▀▀░ ▀ ▀░▀ ▀░░▀
#! ᴅᴇsɪɢɴᴇᴅ & ᴄᴏᴅᴇᴅ ʙʏ ᴛʀɪᴅɪᴀᴍᴏɴᴅ
#! ---------------------------------------------------------------
#! Theme Obsidian - A dark Hexo theme, it's responsive, simple but elegant.
#! Thanks to and inspirated by CSS-Tricks
#! @author: TriDiamond
#! @github: https://github.com/TriDiamond
#! @changelogs: https://github.com/TriDiamond/hexo-theme-obsidian/blob/master/CHANGELOG.md
#! @feedbacks: https://github.com/TriDiamond/hexo-theme-obsidian/issues/new
#! ---------------------------------------------------------------

#! ---------------------------------------------------------------
#!  █▄░█ ▄▀▄ ▀█▀ █▀▀ ▄▀▀
#! █░▀█ █░█ ░█░ █▀▀ ░▀▄
#!▀░░▀ ░▀░ ░▀░ ▀▀▀ ▀▀░ v1.x
#! ---------------------------------------------------------------
#! Since version `v1.3.5` code block highlight has changed from `highlight.js` to
#! `codemirror`, but the Hexo default highlight still need to be disabled to take affect.
#! !! So Please make sure you disabled Hexo's default highlight setting !!
#! ---------------------------------------------------------------
#! Rebuild files after you changed the config:
#! `hexo clean && hexo g`
#! ---------------------------------------------------------------
#! highlight:
#!  enable: false
#!  line_number: true
#!  auto_detect: true
#!  tab_replace:
#! ---------------------------------------------------------------

# Theme version
# !! DO NOT EDIT THIS !!
version: '1.4.5'

# ---------------------------------------------------------------
# Theme default settings
# ---------------------------------------------------------------

# Menu setting | format = title_name: link_url
menu:
  # 文档中心: /
  # 新手指南: /guide
  # SDK下载: /sdkdownload
  # 联络文档: /doclink
  # 常见问题: /faq

# Page custom titles
page_titles:
  categories: 'Categories'
  tags: 'Tags'
  archives: 'Archived'

# Social media links
socials:
  github: 'https://github.com/TriDiamond'
  twitter: 'https://twitter.com/TriDiamond6'
  stackoverflow: 'https://stackoverflow.com/users/7602324/tridiamond?tab=profile'

# Enable table of content
TOC: true

# Home page first post default cover image, default use cover
welcome_cover: /img/cover.jpg

# Article default cover image
cover: /img/welcome-cover.jpg

# Avatar
avatar: https://res.cloudinary.com/tridiamond/image/upload/v1573019751/TriDiamond_logo_ui_xeublz.jpg

# Disable default scrollbar
scrollbar: true

# Website keywords used for SEO
keywords: TriDiamond Obsidian

# Website slogans
descriptionOne: 'Think like an artist, develop like an artisan'
descriptionTwo: '艺术家思维去思考问题，工匠创造精神去开发'

# If you use google analytics, please fill in the ID
google_analytics: 'UA-149874671-1'

# Website favicon
favicon: /img/favicon.png

# rss file
rss: atom.xml

# ---------------------------------------------------------------
# Article Music settings
# ---------------------------------------------------------------

# Auto play article audio
autoplay: false

# default mp3 file 背景音乐
mp3:
  - statics/chengdu.mp3

# ---------------------------------------------------------------
# Plugins
# ---------------------------------------------------------------

# Gitalk comment plugin
# see https://github.com/gitalk/gitalk
gitalk:
  enable: false
  autoExpand: true
  clientID: 'ec894e2b66f752e8b7fb'
  clientSecret: '3ccc2e92bb350688fe2c2dc2930189b62622bfb1'
  repo: 'blog-comments'
  owner: 'TriDiamond'
  admin: ['TriDiamond']
  # Ensure uniqueness and length less than 50
  id: location.pathname
  # Facebook-like distraction

# valine进阶版，解决valine数据不安全的问题
waline:
  enable: true
  js: //cdn.jsdelivr.net/npm/@waline/client/dist/Waline.min.js
  path: location.pathname # 全局评论地址
  meta: ['nick','mail'] # waline 提交者属性
  requiredFields: []  # ['nick','mail']
  placeholder: 快来发表建议吧~  # 评论占位提示
  serverURL: https://hexo-hero-doc.vercel.app # Waline的服务端地址（必填） 
  avatar: monsterid # gravatar style 头像样式  mp,identicon,monsterid,wavatar,retro,hide,robohash	
  pageSize: 0 # 评论每页显示数量   改成0就变成了留言板
  lang: zh-CN
  visitor: true # 统计访问量
  highlight: true # 代码高亮

# Valine comment plugin (recommended!)  
# see https://valine.js.org/quickstart.html valine 无需登录
valine:
  enable: false
  app_id: QHCOIEBlyjBUMAjaE5ilzafk-gzGzoHsz
  app_key: ggeGwz8ypB9uiAIYSRH5T0PF
  notify: false
  verify: false
  avatar: 'mp'
  placeholder: 'Leave your throughs behind~'
  visitor: true

# Enable symbols-count-time plugin
# see https://github.com/theme-next/hexo-symbols-count-time  字数统计，计算出大概需要的阅读时间
symbols_count_time:
  enable: true
  wordCount: true
  readCount: true
  awl: 4
  wpm: 275
  suffix: mins.

# Enable html truncate
# see https://github.com/TriDiamond/hexo-html-truncate
html_truncate:
  enable: true
  # Characters kept for posts
  postLength: 250
  # Characters kept for cover posts
  coverLength: 100
  ellipsis: '...'
  # Excluding html tags
  excludes: ['img', 'h1', 'h2']
  # Characters count including white spaces
  keepWhitespaces: true
  # Reserving the last complete word, without breaking the word
  reserveLastWord: true

# Enable Busuanzi statistic plugin   使用Gitalk作为评论插件可以打开 busuanzi 文章详情页就会显示文章浏览量统计
# see http://ibruce.info/2015/04/04/busuanzi/  
busuanzi:
  enable: true

#Enable social media sharing  分享插件
sharejs:
  enable: false
  disabled: 'facebook,douban,linkedin,diandian,tencent,google'

# Use codemirror instead of highlight js for better colors
# if you want more language support check the modes list at official website
# modes see: https://codemirror.net/mode/
# see https://codemirror.net/
# 使用了codemirror替换了highlight.js，代码高亮更加完善，也更接近IDE的高亮样式
# 默认已经填入了一些语言的mode支持，如果你需要其他语言的支持，请查看codemirror官网的mode
# modes文档请看: https://codemirror.net/mode/
# codemirror官网： https://codemirror.net/
# 默认支持了：JS, HTML, CSS, PHP, JAVA, C, C#, C++, SHELL, PYTHON.
codemirror:
  modes: ['javascript', 'css', 'xml', 'htmlmixed', 'clike', 'php', 'shell', 'python']

# Enabling mathjax support 数学公式
mathjax: true

# custom header HTML
header_html: ''

# custom footer HTML
footer_html: '
<!-- 例：百度统计 -->
<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?your_code";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>
'
# Show previous post and next post in post footer if exists
# Available values: true | false
# 底部上一篇下一篇
post_navigation: false

#定义sdk 基本信息
sdk:
  英雄USDK: usdk
  官方SDK: osdk
  市场SDK: msdk
#子项value首位必须用空格和冒号隔开  
usdk:
  description: 官方+全球+联运SDK聚合工具  只需加入一次USDK即可批量打出一体SDK包体
  clientdoc: Android-JAVA/IOS-OC/UE4/Unity/H5
  serverdoc: Android-JAVA
osdk:
  description: 一套拥有独立发行能力的SDK  包含登录，支付等功能
  clientdoc: Android-JAVA/IOS-OC
  serverdoc: Android-JAVA
msdk:
  description: 聚合了可持续市场统计分析
  clientdoc: Android-JAVA/IOS-OC
  serverdoc:  
  
#定义主页配置信息
indexconfig:
  新手指南: guide--/img/icon_guide.png
  SDK下载: sdkdownload--/img/icon_download.png
  联络文档: doclink--/img/icon_link.png
  常见问题: faq--/img/icon_faq.png